version: '3.4'

networks:
  dev:
    driver: bridge

services:
  labb1publisering:
    image: docker.io/frampt/labb1publisering
    depends_on:
      - dig_api
    container_name: brocontainer_5
    ports:
      - "8081:80"  # Change the host port to 8081
    build:
        context: ./Labb1Publisering
        dockerfile: Dockerfile
    networks:
      - dev

  dig_api:
    image: docker.io/frampt/frampt
    container_name: brocontainer_4
    ports:
      - "8080:80"
    build:
      context: ./DIG_API
      dockerfile: Dockerfile
    networks:
      - dev
