version: '3.4'

networks:
  dev:
    driver: bridge

services:
  labb1publisering:
    image: frampt/labb1publisering:dev
    depends_on:
      - dig_api
    container_name: brocontainer_5
    ports:
      - "8081:80"  # Change the host port to 8081
    build:
        context: ./labb1publisering
        dockerfile: Dockerfile
    networks:
      - dev

  dig_api:
    image: frampt/digapi:dev
    container_name: brocontainer_4
    ports:
      - "8080:80"
    build:
      context: ./DIG_API
      dockerfile: Dockerfile
    networks:
      - dev
